@api = http://127.0.0.1:4000/api/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYmEzNzMwOWUzODc2YzY3ZTdmNmE4YSIsImlhdCI6MTY3MzQ1MjgwNywiZXhwIjoxNjczNTM5MjA3fQ.7giLx61jXnszJe1FdqWZf66qZVlleIQVS5-DTWkoG5M

### Get products
GET {{api}}
Content-Type: application/json

### Get product
GET {{api}}/63bedd8d18079124f6cba0fc
Content-Type: application/json

### Create product
POST {{api}}
Content-Type: application/json
x-access-token: {{token}}

{
  "name": "nutella",
  "price": 6,
  "measure": "gr",
  "type": ["filling", "cream"]
}

### Edit product
PUT {{api}}/63bedd8d18079124f6cba0fc
Content-Type: application/json
x-access-token: {{token}}

{
  "name": "nutella",
  "price": 10,
  "measure": "gr",
  "type": ["filling", "cream"]
}

### Delete product
DELETE {{api}}/63ba418c8814451df7a1da3e
Content-Type: application/json
x-access-token: {{token}}
